name: Publish POST

on:
  push:
    paths:
      - 'posts/**/*.md'
jobs:
  changes:
    runs-on: ubuntu-latest
    environment: Supabase

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          json: "true"
          write_output_files: true

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file was changed"
          done

      - name: Install dependencies
        run: npm ci

      - name: Run JavaScript script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          added_files: ${{ steps.changed-files.outputs.added_files }}
          deleted_files: ${{ steps.changed-files.outputs.deleted_files }}
          modified_files: ${{ steps.changed-files.outputs.modified_files }}
          copied_files: ${{ steps.changed-files.outputs.copied_files }}
          renamed_files: ${{ steps.changed-files.outputs.renamed_files }}

        run: node post.mjs
